services:
  worker:
    command: celery -A backend.app.celery_app.celery worker -l info --concurrency=4

  redis:
    command: redis-server --save 60 1 --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
